//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCalculations.Calculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculator.CalculatorSoap")]
    public interface CalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        double Add(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AddAsync(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        double Subtract(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SubtractAsync(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        double Multiply(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        double Divide(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DivideAsync(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SqrRoot", ReplyAction="*")]
        double SqrRoot(double f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SqrRoot", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SqrRootAsync(double f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Halve", ReplyAction="*")]
        double Halve(double f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Halve", ReplyAction="*")]
        System.Threading.Tasks.Task<double> HalveAsync(double f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quarter", ReplyAction="*")]
        double Quarter(double f1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quarter", ReplyAction="*")]
        System.Threading.Tasks.Task<double> QuarterAsync(double f1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorSoapChannel : TestCalculations.Calculator.CalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorSoapClient : System.ServiceModel.ClientBase<TestCalculations.Calculator.CalculatorSoap>, TestCalculations.Calculator.CalculatorSoap {
        
        public CalculatorSoapClient() {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double f1, double f2) {
            return base.Channel.Add(f1, f2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double f1, double f2) {
            return base.Channel.AddAsync(f1, f2);
        }
        
        public double Subtract(double f1, double f2) {
            return base.Channel.Subtract(f1, f2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double f1, double f2) {
            return base.Channel.SubtractAsync(f1, f2);
        }
        
        public double Multiply(double f1, double f2) {
            return base.Channel.Multiply(f1, f2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double f1, double f2) {
            return base.Channel.MultiplyAsync(f1, f2);
        }
        
        public double Divide(double f1, double f2) {
            return base.Channel.Divide(f1, f2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double f1, double f2) {
            return base.Channel.DivideAsync(f1, f2);
        }
        
        public double SqrRoot(double f1) {
            return base.Channel.SqrRoot(f1);
        }
        
        public System.Threading.Tasks.Task<double> SqrRootAsync(double f1) {
            return base.Channel.SqrRootAsync(f1);
        }
        
        public double Halve(double f1) {
            return base.Channel.Halve(f1);
        }
        
        public System.Threading.Tasks.Task<double> HalveAsync(double f1) {
            return base.Channel.HalveAsync(f1);
        }
        
        public double Quarter(double f1) {
            return base.Channel.Quarter(f1);
        }
        
        public System.Threading.Tasks.Task<double> QuarterAsync(double f1) {
            return base.Channel.QuarterAsync(f1);
        }
    }
}
